# Publish joint states 
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Head position Controllers
head_position_controller:
  type: effort_controllers/JointPositionController
  joint: spherebot_head_joint
  pid: {p: 100.0, i: 0.01, d: 0.0}

isocket_position_controller:
  type: effort_controllers/JointPositionController
  joint: spherebot_isocket_joint
  pid: {p: 100.0, i: 0.01, d: 0.0}

# Arm position Controllers
arm_wheel_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_wheel_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

arm_forearm_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_forearm_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

arm_wrist_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_wrist_joint
  pid: {p: 100.0, i: 0.01, d: 0.0}

arm_hand_left_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_hand_left_joint
  pid: {p: 100.0, i: 0.01, d: 0.0}

arm_hand_right_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_hand_right_joint
  pid: {p: 100.0, i: 0.01, d: 0.0}

arm_finger_left_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_finger_left_joint
  pid: {p: 100.0, i: 0.01, d: 0.0}

arm_finger_right_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_finger_right_joint
  pid: {p: 100.0, i: 0.01, d: 0.0}


  